// tests/ghost.plan.test.js
// Generated by: Qwen 2.5 72B (via OpenRouter)
// Reviewed by: DeepSeek Chat (score: 0.90)
// Verified + fixed by: Claude (Head of Engineering)
const test = require('node:test');
const assert = require('assert');
const fetch = require('node-fetch');
const BASE_URL = process.env.TEST_BASE_URL || 'http://localhost:3000';

test('POST /ghost/plan returns valid JSON structure', { timeout: 30000 }, async () => {
  const response = await fetch(`${BASE_URL}/ghost/plan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ goal: "Zeige mir wie ich einen neuen Agenten anlege", mode: "demo" })
  });

  assert.strictEqual(response.status, 200);
  const json = await response.json();
  assert.strictEqual(typeof json, 'object');
  // LLM kann Plan oder Rückfrage liefern — beides valide
  assert(typeof json.needsClarification === 'boolean');
  if (!json.needsClarification) {
    assert(json.plan && typeof json.plan === 'object');
  } else {
    assert(typeof json.question === 'string');
  }
});

test('POST /ghost/plan build mode returns valid response', { timeout: 30000 }, async () => {
  const response = await fetch(`${BASE_URL}/ghost/plan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ goal: "Navigiere zu den Agents und erstelle einen neuen", mode: "build" })
  });

  assert.strictEqual(response.status, 200);
  const json = await response.json();
  assert.strictEqual(typeof json, 'object');
  assert(typeof json.needsClarification === 'boolean');
});

test('POST /ghost/plan with max-length goal (500 chars)', { timeout: 30000 }, async () => {
  const response = await fetch(`${BASE_URL}/ghost/plan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ goal: "A".repeat(500), mode: "build" })
  });

  // Validation rejects 500-char goal (>500 chars blocked, exactly 500 allowed)
  assert([200, 400].includes(response.status));
  const json = await response.json();
  assert.strictEqual(typeof json, 'object');
});

test('POST /ghost/plan with special characters in goal', { timeout: 30000 }, async () => {
  const response = await fetch(`${BASE_URL}/ghost/plan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ goal: "Agenten mit !@#$% anlegen", mode: "build" })
  });

  assert.strictEqual(response.status, 200);
  const json = await response.json();
  assert.strictEqual(typeof json, 'object');
});

test('POST /ghost/plan with invalid mode returns 400', { timeout: 30000 }, async () => {
  const response = await fetch(`${BASE_URL}/ghost/plan`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ goal: "Zeige mir Agenten", mode: "invalid" })
  });

  assert.strictEqual(response.status, 400);
  const json = await response.json();
  assert(json.error);
});
