/**
 * KI-OS — (C) 2026 Ingo Schaffer
 * https://ki-os.org
 */
"use strict";
const { createStoreBackend } = require('../state/store.backend');
const backend = createStoreBackend({ name: 'tenant-store', backendEnvKey: 'TENANT_STORE_BACKEND', filePathEnvKey: 'TENANT_STORE_PATH', tableEnvKey: 'TENANT_STORE_TABLE', defaultFileName: '.ki-os-tenants.json', defaultTableName: 'ki_os_tenants', partitionKey: 'tenants', defaultValueFactory: () => ({ tenants: [] }) });
let state = load();
function defaultTenant() { return { tenantId: 'default', name: 'Default', status: 'active', policies: [], policyOverrides: {}, connectors: [], workspaces: [], projects: [], orgs: [], billing: { budgetCents: 0, usageHooks: [] }, residency: 'eu', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }
function normalizeTenant(input = {}) { return { tenantId: String(input.tenantId || input.id || 'default'), name: input.name || String(input.tenantId || input.id || 'default'), status: input.status || 'active', policies: Array.isArray(input.policies) ? input.policies : [], policyOverrides: input.policyOverrides && typeof input.policyOverrides === 'object' ? input.policyOverrides : {}, connectors: Array.isArray(input.connectors) ? input.connectors : [], workspaces: Array.isArray(input.workspaces) ? input.workspaces : [], projects: Array.isArray(input.projects) ? input.projects : [], orgs: Array.isArray(input.orgs) ? input.orgs : [], billing: { budgetCents: Number(input.billing?.budgetCents || input.budgetCents || 0), usageHooks: Array.isArray(input.billing?.usageHooks) ? input.billing.usageHooks : [] }, residency: input.residency || 'eu', createdAt: input.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; }
function load() { const raw = backend.read() || { tenants: [] }; const items = Array.isArray(raw.tenants) ? raw.tenants.map(normalizeTenant) : []; if (!items.find((t) => t.tenantId === 'default')) items.unshift(defaultTenant()); return { tenants: items }; }
function persist() { backend.write(state); }
function resetTenantStore() { state = { tenants: [defaultTenant()] }; backend.remove(); persist(); return state; }
function listTenants() { state = load(); return state.tenants.slice(); }
function getTenant(tenantId = 'default') { state = load(); return state.tenants.find((tenant) => tenant.tenantId === String(tenantId || 'default')) || null; }
function summarizeTenant(tenantId = 'default') { const tenant = getTenant(tenantId); if (!tenant) return null; return { tenantId: tenant.tenantId, name: tenant.name, status: tenant.status, policies: tenant.policies.length, connectors: tenant.connectors.length, workspaces: tenant.workspaces.length, budgetCents: Number(tenant.billing?.budgetCents || 0), residency: tenant.residency }; }
function upsertTenant(input = {}) { state = load(); const tenant = normalizeTenant(input); const idx = state.tenants.findIndex((item) => item.tenantId === tenant.tenantId); if (idx >= 0) state.tenants[idx] = { ...state.tenants[idx], ...tenant, updatedAt: new Date().toISOString() }; else state.tenants.push(tenant); persist(); return getTenant(tenant.tenantId); }
function createWorkspace(tenantId, input = {}) { const tenant = getTenant(tenantId); if (!tenant) throw new Error('tenant_not_found'); const workspaceId = String(input.workspaceId || input.id || `ws-${Date.now()}`).trim(); const item = { workspaceId, tenantId, name: input.name || workspaceId, createdAt: new Date().toISOString() }; tenant.workspaces = tenant.workspaces.filter((it) => it.workspaceId !== workspaceId); tenant.workspaces.push(item); persist(); return item; }
function createProject(tenantId, input = {}) { const tenant = getTenant(tenantId); if (!tenant) throw new Error('tenant_not_found'); const projectId = String(input.projectId || input.id || `proj-${Date.now()}`).trim(); const item = { projectId, tenantId, orgId: input.orgId || null, name: input.name || projectId, createdAt: new Date().toISOString() }; tenant.projects = tenant.projects.filter((it) => it.projectId !== projectId); tenant.projects.push(item); persist(); return item; }
function createOrg(tenantId, input = {}) { const tenant = getTenant(tenantId); if (!tenant) throw new Error('tenant_not_found'); const orgId = String(input.orgId || input.id || `org-${Date.now()}`).trim(); const item = { orgId, tenantId, name: input.name || orgId, createdAt: new Date().toISOString() }; tenant.orgs = tenant.orgs.filter((it) => it.orgId !== orgId); tenant.orgs.push(item); persist(); return item; }
function addBillingHook(tenantId, hook = {}) { const tenant = getTenant(tenantId); if (!tenant) throw new Error('tenant_not_found'); const item = { hookId: String(hook.hookId || `bill-${Date.now()}`), event: hook.event || 'usage.recorded', target: hook.target || 'internal', active: hook.active !== false, createdAt: new Date().toISOString() }; tenant.billing = tenant.billing || { usageHooks: [], budgetCents: 0 }; tenant.billing.usageHooks = Array.isArray(tenant.billing.usageHooks) ? tenant.billing.usageHooks : []; tenant.billing.usageHooks.push(item); persist(); return item; }
function buildIsolationPayload(ctx = {}, requestedTenantId = 'default') { const actorTenantId = String(ctx?.pki?.tenantId || ctx?.tenantId || 'default'); const tenantId = requestedTenantId || actorTenantId; const allowed = actorTenantId === tenantId || ['admin', 'auditor'].includes(String(ctx?.pki?.role || '').toLowerCase()); return { actorTenantId, tenantId, allowed, isolated: actorTenantId === tenantId }; }
function assertTenantAccess(ctx = {}, requestedTenantId = 'default') { const payload = buildIsolationPayload(ctx, requestedTenantId); if (!payload.allowed) { const error = new Error('tenant_isolation_violation'); error.statusCode = 403; error.payload = payload; throw error; } return payload; }
function getTenantPolicyOverride(tenantId = 'default') { return getTenant(tenantId)?.policyOverrides || {}; }
function setTenantPolicyOverride(tenantId = 'default', overrides = {}) { const tenant = getTenant(tenantId); if (!tenant) throw new Error('tenant_not_found'); tenant.policyOverrides = { ...(tenant.policyOverrides || {}), ...(overrides || {}) }; tenant.updatedAt = new Date().toISOString(); persist(); return tenant.policyOverrides; }
function getEffectivePolicyView(tenantId = 'default') { const tenant = getTenant(tenantId); if (!tenant) return null; return { tenantId: tenant.tenantId, policies: tenant.policies, overrides: tenant.policyOverrides || {}, residency: tenant.residency, budgetCents: Number(tenant.billing?.budgetCents || 0) }; }
function getProductCorePayload() { state = load(); return { success: true, version: 'v1', totalTenants: state.tenants.length, activeTenants: state.tenants.filter((tenant) => tenant.status === 'active').length, billingReady: true, tenantScopedPolicies: state.tenants.reduce((sum, tenant) => sum + tenant.policies.length, 0), tenantScopedConnectors: state.tenants.reduce((sum, tenant) => sum + tenant.connectors.length, 0), workspaces: state.tenants.reduce((sum, tenant) => sum + tenant.workspaces.length, 0), backend: backend.info() }; }
module.exports = { listTenants, summarizeTenant, getTenant, upsertTenant, createWorkspace, createProject, createOrg, addBillingHook, buildIsolationPayload, assertTenantAccess, getProductCorePayload, resetTenantStore, getTenantPolicyOverride, setTenantPolicyOverride, getEffectivePolicyView };