/**
 * KI-OS — (C) 2026 Ingo Schaffer
 * https://ki-os.org
 */
"use strict";
const Observability = require('../core/observability.service');
const { listRoutingScorecards } = require('../routing/dynamic-routing.service');
const federation = require('../federation/federation.service');
const { createStoreBackend } = require('../state/store.backend');
const backend = createStoreBackend({ name: 'economic-store', backendEnvKey: 'ECONOMIC_STORE_BACKEND', filePathEnvKey: 'ECONOMIC_OPTIMIZER_STORE_PATH', tableEnvKey: 'ECONOMIC_STORE_TABLE', defaultFileName: '.ki-os-economic-optimizer.json', defaultTableName: 'ki_os_economic_store', partitionKey: 'economic_store', defaultValueFactory: () => defaultState() });
function defaultProfiles() { return [{ profileId: 'balanced-default', label: 'Balanced Default', minTrustScore: 75, minOutcomeCoverage: 0.55, downshiftLatencyMs: 1100, highValueBudgetCents: 250, downshiftEnabled: true, highValueEscalationEnabled: true, reversibility: 'manual_override' }, { profileId: 'cost-first', label: 'Cost First', minTrustScore: 70, minOutcomeCoverage: 0.5, downshiftLatencyMs: 1400, highValueBudgetCents: 180, downshiftEnabled: true, highValueEscalationEnabled: false, reversibility: 'manual_override' }, { profileId: 'roi-first', label: 'ROI First', minTrustScore: 82, minOutcomeCoverage: 0.65, downshiftLatencyMs: 900, highValueBudgetCents: 400, downshiftEnabled: false, highValueEscalationEnabled: true, reversibility: 'manual_override' }]; }
function defaultState() { return { version: 'v1', profiles: defaultProfiles(), decisions: [], scorecards: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }
let state = load();
function load() { return backend.read() || defaultState(); }
function persist(snapshot = state) { snapshot.updatedAt = new Date().toISOString(); backend.write(snapshot); state = snapshot; }
function resetEconomicStore() { state = defaultState(); backend.remove(); persist(); return state; }
function listProfiles() { state = load(); return state.profiles.slice(); }
function getProfile(profileId = 'balanced-default') { state = load(); return state.profiles.find((item) => item.profileId === profileId) || state.profiles[0]; }
function computeEconomicScorecard(limit = 20) { state = load(); const routing = listRoutingScorecards(limit); const benchmarks = federation.listBenchmarks(limit); const items = routing.map((card) => { const benchmark = benchmarks.find((b) => b.provider === card.provider && b.model === card.model) || null; const outcomeCoverage = Number(benchmark?.avgOutcomeCoverage ?? card.avgOutcomeCoverage ?? 0); const trustScore = Number(benchmark?.avgTrustScore ?? card.avgTrustScore ?? 0); const latencyMs = Number(benchmark?.avgLatencyMs ?? card.avgLatencyMs ?? 0); const costPressure = card.model && /opus|pro/i.test(card.model) ? 'high' : /haiku|flash|deepseek/i.test(card.model) ? 'low' : 'medium'; const economicScore = Number((outcomeCoverage * 0.4 + Math.min(1, trustScore / 100) * 0.3 + Math.max(0, Math.min(1, 1800 / Math.max(1, latencyMs || 1800))) * 0.2 + Math.min(1, Number(card.score || 0.5)) * 0.1).toFixed(4)); return { provider: card.provider, model: card.model, totalRuns: card.totalRuns, successRuns: card.successRuns, avgOutcomeCoverage: Number(outcomeCoverage.toFixed(4)), avgTrustScore: Number(trustScore.toFixed(2)), avgLatencyMs: Number(latencyMs.toFixed(2)), routingScore: Number(card.score || 0.5), costPressure, economicScore, recommendation: economicScore >= 0.78 ? 'prioritize' : economicScore >= 0.56 ? 'optimize' : 'deprioritize' }; }); state.scorecards = items; persist(); return items; }
function evaluateEconomicDecision(input = {}) { state = load(); const profile = getProfile(input.profileId); const taskClass = String(input.taskClass || 'default'); const provider = String(input.provider || 'openai'); const model = String(input.model || 'gpt-5.4'); const budgetCents = Number(input.budgetCents || 0); const trustScore = Number(input.trustScore || 0); const outcomeCoverage = Number(input.outcomeCoverage || 0); const latencyMs = Number(input.latencyMs || 0); const roiSignal = Number(input.roiSignal || 0); const scorecards = state.scorecards.length ? state.scorecards : computeEconomicScorecard(20); const related = scorecards.find((item) => item.provider === provider && item.model === model) || null; let action = 'keep'; let reason = 'economic_balance_ok'; let targetModel = model; let targetProvider = provider; if (profile.downshiftEnabled && trustScore >= profile.minTrustScore && outcomeCoverage >= profile.minOutcomeCoverage && latencyMs <= profile.downshiftLatencyMs && budgetCents > 0) { action = 'downshift'; reason = 'safe_quality_budget_optimization'; if (/opus|pro|gpt-5\.4/i.test(model)) { targetModel = /claude/i.test(model) ? 'claude-haiku-4-5-20251001' : /gpt/i.test(model) ? 'gemini-2.0-flash' : model; targetProvider = /gpt/i.test(model) ? 'gemini' : provider; } } if (profile.highValueEscalationEnabled && (roiSignal >= 0.8 || (related && related.economicScore >= 0.8 && outcomeCoverage < profile.minOutcomeCoverage))) { action = 'escalate'; reason = 'high_value_roi_escalation'; targetModel = /claude/i.test(model) ? 'claude-opus-4-6' : 'gpt-5.4'; targetProvider = /claude/i.test(model) ? 'anthropic' : 'openai'; } const decision = { decisionId: `econ-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, profileId: profile.profileId, taskClass, provider, model, budgetCents, trustScore, outcomeCoverage, latencyMs, roiSignal, action, reason, targetProvider, targetModel, audit: { reversible: true, policyProfile: profile.label, benchmarkEconomicScore: related ? related.economicScore : null }, createdAt: new Date().toISOString() }; state.decisions.unshift(decision); state.decisions = state.decisions.slice(0, Number(process.env.ECONOMIC_DECISION_LIMIT || 200)); persist(); Observability.emit('economic.decision.made', { action, reason, provider, model, targetProvider, targetModel, taskClass }); return decision; }
function listDecisions(limit = 50) { state = load(); return state.decisions.slice(0, Math.max(1, Number(limit || 50))); }
function getEconomicPayload() { state = load(); return { success: true, version: '6.3.7-r27-production-backbone', profileCount: state.profiles.length, decisionCount: state.decisions.length, scorecardCount: state.scorecards.length, backend: backend.info(), deliverables: ['Economic Optimization Engine v1', 'Budget/Outcome Policy Profiles v1', 'Economic Scorecard Layer v1', 'Optimization Dashboard v1'] }; }
module.exports = { resetEconomicStore, listProfiles, getProfile, computeEconomicScorecard, evaluateEconomicDecision, listDecisions, getEconomicPayload };